# These are supported funding model platforms

github: https://github.com/ClareBond
liberapay: https://pytorch.org/
custom: https://www.abdn.ac.uk/
custom: https://www.ukri.org/councils/nerc/
custom: https://www.ukri.org/
custom: https://nerc-cdt-oil-and-gas.ac.uk/
custom: https://www.ukri.org/what-we-offer/developing-people-and-skills/nerc/nerc-studentships/directed-training/centres-for-doctoral-training-cdt/cdt-in-oil-and-gas/
